name = "WeakRefStrings"
uuid = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"
authors = ["quinnj <quinn.jacobd@gmail.com>"]
version = "0.6.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
